# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Innoloft-API

on:
  push:
    branches:
      - Site-filme-normale
  workflow_dispatch:

jobs:
  build:
    name: Build .net api
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with: 
          files: 'BE/MoviesAPI/appsettings.json'
        env:
          Authentication.AuthUri: ${{secrets.AUTH_URi}}
          Authentication.TokenUri: ${{secrets.TOKEN_URI}}
          Authentication.Audience: ${{secrets.AUDIENCE}}
          Authentication.ValidIssuer: ${{secrets.VALID_ISSUER}}
          ConnectionStrings.MySqlConn: ${{secrets.MY_SQL_CONNECTION_STRING}}
          
      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: BE/MoviesAPI

      - name: dotnet publish
        run: dotnet publish -c Release -o out
        working-directory: BE/MoviesAPI

      - name: Update Database
        run: |
            dotnet tool install --global dotnet-ef --version 7.0.12
            dotnet tool restore
            dotnet ef database update 
        working-directory: BE/MoviesAPI
        env:
          ConnectionStrings.MySqlConn: ${{secrets.MY_SQL_CONNECTION_STRING}}
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: BE/MoviesAPI/out/*


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MoviesAPI-NET'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D28D8DD4B48B49F0A12F4EB1FF20506E }}
          package: .
